uglifyjs ^
    js/gamedata/crops.js ^
    js/gamedata/enemies.js ^
    js/gamedata/shops.js ^
    js/gamedata/spritedata.js ^
    js/gamedata/misc.js ^
    js/animation/animController.js ^
    js/input.js ^
    js/combat/combat.js ^
    js/animation/combatAnim.js ^
    js/combat/combatmenu.js ^
    js/combat/combatplant.js ^
    js/combat/combatenemyturn.js ^
    js/combat/combatcompost.js ^
    js/combat/combatselectenemy.js ^
    js/combat/combatinbetween.js ^
    js/combat/tutorial.js ^
    js/worldmap/worldmap.js ^
    js/worldmap/shop.js ^
    js/worldmap/collisions.js ^
    js/worldmap/entityHelpers.js ^
    js/worldmap/entities.js ^
    js/playerstats/pausemenu.js ^
    js/playerstats/viewinventory.js ^
    js/playerstats/equipment.js ^
    js/playerstats/farmmod.js ^
    js/playerstats/skilltrees.js ^
    js/playerstats/savemenu.js ^
    js/player.js^
    js/rendering.js ^
    js/main.js ^
-o out.min.js
