var scripts = {
	// Farm: Opening Cutscene
	"farminit0": "_SLEEP:500",
	"farminit1": "pl_MOVE:y10",
	"farminit2": "_CUSTOM:PWIDE",
	"farminit3": "_SLEEP:500",
	"farminit4": "_PLANIM:2,0,1000",
	"farminit5": "_PLANIM:2,1,500",
	"farminit6": "_PLANIM:2,2,1500",
	"farminit7": "_PLANIM:2,1,250",
	"farminit8": "_CUSTOM:PUNWIDE",
	"farminit9": "pl_MOVE:y11",
	"farminit10": "_PLANIM:4,0,1500&pl_SETDIR:3",
	"farminit11": "_TEXT:intro1",
	"farminit12": "nathanA_ISMOVING:true&nathanA_MOVE:x21",
	"farminit13": "_TEXT:intro2&nathanA_ANIMSTATE:[2,3,2,8,true]",
	"farminit14": "_TEXT:intro3",
	"farminit15": "_CLEARTEXT&nathanA_ANIMSTATE:[2,3,1,0,false]&_SLEEP:1000",
	"farminit16": "pl_SETDIR:2&pl_MOVE:y12",
	"farminit17": "_PLANIM:4,0,1000",
	"farminit18": "pl_SETDIR:3&nathanA_ANIMSTATE:[2,4,2,8,true]&_TEXT:intro4",
	"farminit19": "_TEXT:intro(5-6)",
	"farminit20": "_CLEARTEXT&nathanA_ANIMSTATE:[2,4,1,8,false]&_PLANIM:4,3,1500",
	"farminit21": "pl_SETDIR:3&nathanA_ANIMSTATE:[2,4,2,8,true]&_TEXT:intro(7-8)",
	"farminit22": "_CLEARTEXT&nathanA_ANIMSTATE:[0,2,4,8]&nathanA_MOVE:x24",
	"farminit23": "_GO2:[\"producestand\",10,5]",
	// Produce Stand: Opening Cutscene
	"pstand0": "pl_SETDIR:1&hipster_MOVE:x6",
	"pstand1": "hipster_ISMOVING:false&_SLEEP:500",
	"pstand2": "hipster_ANIMSTATE:[2,3,2,8,true]&_TEXT:intro9",
	"pstand3": "bike_VISIBLE:true&hipster_ANIMSTATE:[0,1,4,-1,true]&_CUSTOM:HIPMOV",
	"pstand4": "hipster_ANIMSTATE:[0,3,2,8]&_TEXT:intro10",
	"pstand5": "hipster_ANIMSTATE:[0,2,4,8,false]&_TEXT:intro11",
	"pstand6": "hipster_ISMOVING:true&_TEXT:intro(12-13)",
	"pstand7": "hipster_ISMOVING:false&_TEXT:intro14",
	"pstand8": "hipster_ANIMSTATE:[0,3,2,8,true]&_TEXT:intro(15-19)",
	"pstand9": "hipster_ISMOVING:false&_TEXT:intro20",
	"pstand10": "hipster_ISMOVING:true&_TEXT:intro(21-22)",
	"pstand11": "_CLEARTEXT&hipster_ANIMSTATE:[0,4,4,-1]&_CUSTOM:HIPMOV2",
	"pstand12": "hipster_ANIMSTATE:[0,0,2,-1]&bike_VISIBLE:false&hipster_MOVE:x10",
	"pstand13": "pl_SETDIR:0&convince_VISIBLE:true&hipster_MOVE:x12",
	"pstand14": "pl_SETDIR:3&hipster_MOVE:x20",
	"pstand15": "pl_SETDIR:0&_TEXT:intro23",
	"pstand16": "_CLEARTARGET&hipster_SETTARGET&_CUSTOM:TUTORIAL",
	// Produce Stand: Completion of Opening Cutscene
	"finTut0": "_CUSTOM:LEAVETUTORIAL&_CLEARTARGET&_CUSTOM:FINISHTUTORIALATSTART&_TEXT:Pb0.0",
	"finTut1": "_TEXT:Pb0.1",
	// Produce Stand: Tutorial
	"tutBuddy0": "_TEXT:wantTut,sYes,sNo",
	"tutBuddy1": "?[{\"q\":\"d==0\",\"v\":3},{\"q\":\"d===1\",\"v\":2}]",
	"tutBuddy2": "_TEXT:noTut&_END",
	"tutBuddy3": "_CUSTOM:TUTORIAL",
	// Produce Stand: Completion of Standalone Tutorial
	"finStTut0": "_CUSTOM:LEAVETUTORIAL&_CUSTOM:FINISHTUTORIALSTANDALONE",
	// Produce Stand: Trying to head to Town before going to Farm
	"farmFirst0": "?[{\"q\":\"player.completedQuest('bigBot')\",\"v\":1},{\"q\":\"true\",\"v\":2}]",
	"farmFirst1": "_GO2:[\"firstvillage\",21,1]",
	"farmFirst2": "_TEXT:farmFirst",
	// Produce Stand: Egg Fairy
	"eggfairy0": "?[{\"q\":\"player.completedQuest('badEgg')\",\"v\":1},{\"q\":\"player.completedQuest('goodEgg')\",\"v\":2},{\"q\":\"player.hasItem('egg')\",\"v\":4},{\"q\":\"true\",\"v\":3}]",
	"eggfairy1": "_TEXT:badEggTry&_END",
	"eggfairy2": "_TEXT:goodEggTry&_END",
	"eggfairy3": "_TEXT:lakenoegg&_END",
	"eggfairy4": "_TEXT:lakeegg,sYes,sNo",
	"eggfairy5": "?[{\"q\":\"d==0\",\"v\":7},{\"q\":\"d===1\",\"v\":6}]",
	"eggfairy6": "_TEXT:lakeegg.reject&_END",
	"eggfairy7": "_TEXT:lakeegg.okay&_TAKE:egg,1",
	"eggfairy8": "_TEXT:dotdotdot",
	"eggfairy9": "eggFairy_VISIBLE:true&_TEXT:lakeegg(1-2)",
	"eggfairy10": "_TEXT:lakeegg3,sYes,sNo",
	"eggfairy11": "?[{\"q\":\"d===0\",\"v\":12},{\"q\":\"d===1\",\"v\":14}]",
	"eggfairy12": "_TEXT:lakeeggLie&eggFairy_SHIFTY:2&_TAKE:egg,999&_TAKE:quail,999&_TAKE:goose,999&_TAKE:turkey,999&_TAKE:platypus,999",
	"eggfairy13": "_TEXT:lakeFinish&eggFairy_VISIBLE:false&_COMPLETEQUEST:badEgg&_END",
	"eggfairy14": "_TEXT:lakeeggTruth&eggFairy_SHIFTY:1&_GIVE:egg,1&_GIVE:goldegg,1",
	"eggfairy15": "_TEXT:lakeFinish&eggFairy_VISIBLE:false&_COMPLETEQUEST:goodEgg",
	// Farm: First Boss (Big Bot)
	"bigBot0": "_TEXT:B1.(0-4)",
	"bigBot1": "_FIGHT:bigBot",
	"bigBotL0": "_TEXT:B1.5",
	"bigBotL1": "_FIGHT:bigBot",
	"bigBotW0": "_COMPLETEQUEST:bigBot&_TEXT:Pb1.(0-1)",
	"bigBotW1": "_TEXT:Pb1.2,Pb1.2a,Pb1.2b",
	"bigBotW2": "?[{\"q\":\"d===0\",\"v\":3},{\"q\":\"d===1\",\"v\":4}]",
	"bigBotW3": "_TEXT:Pb1.2a0&_SETSTATE:5&_GIVE:beet,10&_GIVE:banana,5&_GIVE:spinach,5&_GIVE:rhubarb,2&_GIVE:ginger,10",
	"bigBotW4": "_TEXT:Pb1.2b0&_GIVE:~modulator,1",
	"bigBotW5": "_TEXT:Pb1.(3-5)",
	// Misc.: Standard Enemy
	"enemy0": "_CUSTOM:ENEMY0",
	"enemy1": "_CUSTOM:ENEMY1",
	// Farm: Beehive
	"FarmHive0": "targ_VISIBLE:false&_TEXT:hiveGet&_GIVE:~beehive,1&_GIVE:beeB,5",
	"FarmHive1": "_CUSTOM:BEEGUARDIANAPPEAR&_TEXT:FarmHive(0-3)",
	"FarmHive2": "_TEXT:FarmHive4&_CLEARTARGET",
	// Forest: Optional Boss (Turkey)
	"turky0": "_TEXT:bossturky(0-1)",
	"turky1": "_FIGHT:bossturky,turky,turky",
	// Forest: Beehive
	"ForestHive0": "targ_VISIBLE:false&_TEXT:hiveGet&_GIVE:~beehive,1&_GIVE:beeB,5",
	"ForestHive1": "_TEXT:ForestHive(0-1)",
	"ForestHive2": "pl_SETDIR:2&_TEXT:ForestHive2",
	"ForestHive3": "_FIGHT:bear",
	// Forest: Bad Influence Rabbit
	"rabbit0": "?[{\"q\":\"player.completedQuest('rabbitShit')\",\"v\":1},{\"q\":\"true\",\"v\":2}]",
	"rabbit1": "_TEXT:rabbitOut&_END",
	"rabbit2": "_TEXT:rabbit0",
	"rabbit3": "_TEXT:rabbit1,buyfertilizer,sNo",
	"rabbit4": "?[{\"q\":\"d===1\",\"v\":5},{\"q\":\"player.monies < 500\",\"v\":6},{\"q\":\"d===0\",\"v\":7}]",
	"rabbit5": "_TEXT:rabbit2&_END",
	"rabbit6": "_TEXT:rabbit3&_END",
	"rabbit7": "_MONEY:-500&_GIVE:~strongsoil&_COMPLETEQUEST:rabbitShit&_TEXT:rabbit(4-7)",
	// Forest: Sad Fish
	"sadfish0": "?[{\"q\":\"player.completedQuest('fishyTalk')\",\"v\":3},{\"q\":\"true\",\"v\":1}]",
	"sadfish1": "targ_VISIBLE:true&_TEXT:fishyFriend(0-1)",
	"sadfish2": "_COMPLETEQUEST:fishyTalk&_TEXT:fishyFriend2&_SETSTATE:4",
	"sadfish3": "targ_VISIBLE:true&_TEXT:fishyFriendX",
	"sadfish4": "targ_VISIBLE:false&_QUIT",
	// Forest: Lime
	"lime0": "?[{\"q\":\"player.completedQuest('limeAndTheCoconut')\",\"v\":3},{\"q\":\"player.hasQuest('limeAndTheCoconut')\",\"v\":4},{\"q\":\"true\",\"v\":1}]",
	"lime1": "_STARTQUEST:limeAndTheCoconut&_TEXT:lime(0-2)",
	"lime2": "_TEXT:lime3&_END",
	"lime3": "_TEXT:lime.complete&_END",
	"lime4": "_CUSTOM:LIMESTART",
	"lime5": "??LIMENEXT",
	"lime6": "_TEXT:lime.lemon2",
	"lime7": "_TEXT:lime.lemon3&_END",
	"lime8": "_TEXT:lime.banana2",
	"lime9": "_COMPLETEQUEST:limeAndTheCoconut&_TAKE:banana,1&_GIVE:corn,10&_TEXT:lime.banana3&_END",
	"lime10": "_TEXT:lime.corn2",
	"lime11": "_COMPLETEQUEST:limeAndTheCoconut&_TAKE:corn,1&_GIVE:banana,10&_TEXT:lime.corn3&_END",
	"lime12": "_COMPLETEQUEST:limeAndTheCoconut&_TAKE:goldegg,1&_GIVE:coconut,2&_TEXT:lime.egg(2-3)",
	// Below Village: Beehive
	"BelowHive0": "targ_VISIBLE:false&_TEXT:hiveGet&_GIVE:~beehive,1&_GIVE:beeB,5&_CLEARTARGET",
	// Research Lab: Seed Shooters
	"seedShot0": "?[{\"q\":\"game.target.hasShot-- > 0\",\"v\":1},{\"q\":\"true\",\"v\":2}]",
	"seedShot1": "_QUIT",
	"seedShot2": "_TEXT:seedshot&_CUSTOM:SEEDSHOT",
	"seedShot3": "?[{\"q\":\"player.health > 0\",\"v\":1},{\"q\":\"true\",\"v\":4}]",
	"seedShot4": "_TEXT:seedshotdeath",
	"seedShot5": "_CUSTOM:SEEDSHOTKILL",
	// Research Lab: RAPBATTLE
	"rap0": "?[{\"q\":\"player.completedQuest('rapbattle')\",\"v\":3},{\"q\":\"player.hasQuest('rapbattle')\",\"v\":4},{\"q\":\"true\",\"v\":1}]",
	"rap1": "_STARTQUEST:rapbattle&_TEXT:rap(0-2)",
	"rap2": "_TEXT:rap3&_END",
	"rap3": "_TEXT:rap.thanks&_END",
	"rap4": "_CUSTOM:RAPSTART",
	"rap5": "??RAPNEXT",
	"rap6": "_TAKE:garlic,1&_TEXT:rap.garlic(2-5)",
	"rap7": "_COMPLETEQUEST:rapbattle&_GIVE:battery,10&_TEXT:rap.normalgift&_END",
	"rap8": "_TAKE:rice,1&_TEXT:rap.rice(2-3)",
	"rap9": "_TEXT:rap.rice4&_SETSTATE:7",
	"rap10": "_TEXT:rap.coconut(2-6)",
	"rap11": "_COMPLETEQUEST:rapbattle&_TAKE:coconut,1&_GIVE:gmocorn,2&_TEXT:rap.coconut7&_END",
	// Research Lab: Second Boss (Jeff)
	"jeff0": "_TEXT:B2.(0-11)",
	"jeff1": "_FIGHT:ScienceMan",
	"jeffL0": "_TEXT:B2.12",
	"jeffL1": "_FIGHT:ScienceMan",
	"jeffW0": "_COMPLETEQUEST:researchLab&_TEXT:Pb2.(0-9)",
	"jeffW1": "_TEXT:Pb2.10,Pb2.10a,Pb2.10b,Pb2.10c",
	"jeffW2": "?[{\"q\":\"d===0\",\"v\":3},{\"q\":\"d===1\",\"v\":4},{\"q\":\"d===2\",\"v\":5}]",
	"jeffW3": "_TEXT:Pb2.10a0&_SETSTATE:6&_GIVE:~shooter,1",
	"jeffW4": "_TEXT:Pb2.10b0&_SETSTATE:6&_GIVE:apple,10&_GIVE:apricot,10&_GIVE:kiwi,5&_GIVE:mango,5&_GIVE:lemon,5",
	"jeffW5": "_TEXT:Pb2.10c0&_LEVELUP&_LEVELUP&_LEVELUP",
	"jeffW6": "_TEXT:Pb2.(11-13)",
};